### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by foliwe** [GeorgioWan/typedjq-rails#1]
Hi, I followed your tutorials I can't see any text. does this works with rails 5

**Comment by GeorgioWan** [comment]
Hi @foliwe ,
It works on Rails 5, maybe you should try `$->` to start to typed 😋 
```coffee
$->
  $(".yourelement").typed
    strings: ["Typed.js is a <strong>jQuery</strong> plugin."]
```

> If there doesn't do anything, please post your code, I'll check it!
